spring.application.name=jobportal

# jdbc
spring.datasource.username=jobportal
spring.datasource.password=jobportal
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal

# specify file upload max parts
server.tomcat.max-part-count=50
